# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'PiChat' do
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'LeanCloudFeedback'
pod 'JSQMessagesViewController'
pod 'MWPhotoBrowser'
end

target 'PiChatTests' do

end

target 'PiChatUITests' do

end

