# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

inhibit_all_warnings!

target 'PiChat' do
pod 'AVOSCloud'
pod 'AVOSCloudIM'
pod 'LeanCloudFeedback'
pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
pod 'MWPhotoBrowser'
pod 'MBProgressHUD'
pod 'Masonry'
pod 'GJAlertController'
end

target 'PiChatTests' do

end

target 'PiChatUITests' do

end

